### ISSUE TITLE
More info possibly?

### ISSUE THREAD

**Issue by OntheDOL** [thekroko/uthgard-opensource#1]
Hi there, 
The pathing is an awesome release and I'd really like to try and integrate your work with to release to the rest of DOL. I wonder if you could share more information regarding files under the namespame DOL.Geometry (custom  vector3 methods? ) and DOL.GS.GameObjects. 

Thanks.

**Comment by thekroko** [comment]
You can use this Vector3 impl as a drop-in replacement: https://github.com/dickiepotter/Vector
